package gm.rh.modelo;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Entity representing an employee in the system.
 * Maps to the corresponding database table and contains the basic information
 * of each employee.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Empleado {

    /**
     * Unique identifier for the employee.
     * Automatically generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Integer idEmpleado;

    /**
     * Full name of the employee.
     */
    String nombre;

    /**
     * Department to which the employee belongs.
     */
    String departamento;

    /**
     * Employee's salary.
     */
    Double sueldo;
}
